### ISSUE TITLE
TypeError with `-n, --no-filter` (version 1.3)

### ISSUE THREAD

**Issue by pierreganty** [jrfonseca/xdot.py#121]
`xdot`version 1.3 was installed via homebrew and the invokation without options works fine. With version 1.2 the `--no-filter` option was working fine but not anymore with version 1.3. Now I have the following trace reporting a `TypeError`:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/xdot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/xdot/1.3/libexec/lib/python3.11/site-packages/xdot/__main__.py", line 82, in main
    win.open_file(inputfile)
  File "/opt/homebrew/Cellar/xdot/1.3/libexec/lib/python3.11/site-packages/xdot/ui/window.py", line 730, in open_file
    self.set_dotcode(fp.read(), filename)
  File "/opt/homebrew/Cellar/xdot/1.3/libexec/lib/python3.11/site-packages/xdot/ui/window.py", line 712, in set_dotcode
    if self.dotwidget.set_dotcode(dotcode, filename):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/xdot/1.3/libexec/lib/python3.11/site-packages/xdot/ui/window.py", line 148, in set_dotcode
    if self._set_dotcode(dotcode, filename, center=center):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/xdot/1.3/libexec/lib/python3.11/site-packages/xdot/ui/window.py", line 139, in _set_dotcode
    self.set_xdotcode(xdotcode, center=center)
  File "/opt/homebrew/Cellar/xdot/1.3/libexec/lib/python3.11/site-packages/xdot/ui/window.py", line 160, in set_xdotcode
    stdout = subprocess.check_output([self.filter, '-V'], stderr=subprocess.STDOUT)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466,
 in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548,
 in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026
, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1824
, in _execute_child
    and os.path.dirname(executable)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 152, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by pierreganty** [comment]
@jrfonseca did you get a chance to look at the issue?

**Comment by jrfonseca** [comment]
Fixed now.  It shall be included on the next version.  Thanks for the report.

**Comment by pierreganty** [comment]
Thank you!
