### ISSUE TITLE
RuntimeError: could not open display

### ISSUE THREAD

**Issue by yjx723** [jrfonseca/xdot.py#20]
It can't create the GTK display, any solutions?
--------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/xdot", line 9, in <module>
    load_entry_point('xdot==0.6', 'gui_scripts', 'xdot')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/xdot-0.6-py2.6.egg/xdot.py", line 34, in <module>
    import gtk
  File "/usr/lib64/python2.6/site-packages/gtk-2.0/gtk/__init__.py", line 64, in <module>
    _init()
  File "/usr/lib64/python2.6/site-packages/gtk-2.0/gtk/__init__.py", line 52, in _init
    _gtk.init_check()
RuntimeError: could not open display

**Comment by jrfonseca** [comment]
It's failing on `import gtk`.

This looks like a fundamental problem with your system's setup: either X server, GTK, or PyGTK.

As it doesn't look like anything to do with xdot itself I don't think I can help.
