### ISSUE TITLE
Failure to render attached dot file

### ISSUE THREAD

**Issue by thomasdullien** [jrfonseca/xdot.py#45]
Hey there,

current trunk of xdot throws a python exception & stack trace when the attached file is rendered.
[vma_tree.dot.txt](https://github.com/jrfonseca/xdot.py/files/973654/vma_tree.dot.txt)

Stack trace looks like this:
Traceback (most recent call last):
  File "xdot/ui/window.py", line 638, in on_open
    self.open_file(filename)
  File "xdot/ui/window.py", line 611, in open_file
    self.set_dotcode(fp.read(), filename)
  File "xdot/ui/window.py", line 593, in set_dotcode
    if self.dotwidget.set_dotcode(dotcode, filename):
  File "xdot/ui/window.py", line 133, in set_dotcode
    self.set_xdotcode(xdotcode)
  File "xdot/ui/window.py", line 147, in set_xdotcode
    parser = XDotParser(xdotcode)
  File "xdot/dot/parser.py", line 429, in __init__
    DotParser.__init__(self, lexer)
  File "xdot/dot/parser.py", line 303, in __init__
    Parser.__init__(self, lexer)
  File "xdot/dot/parser.py", line 56, in __init__
    self.lookahead = next(self.lexer)
TypeError: instance has no next() method

**Comment by thomasdullien** [comment]
Hey there,

update: Issue disappears when using python3 :-)

**Comment by jrfonseca** [comment]
Yes, xdot now requires Python 3.

I'm surprised xdot goes that far with Python 2 without triggering any syntax errors.
