### ISSUE TITLE
Unicode issue in Windows

### ISSUE THREAD

**Issue by tumagonx** [jrfonseca/xdot.py#46]
windows 10 64bit
python 3.4 64bit
pygobject 3.24
graphviz-py 0.7.1
graphviz 2.36
xdot 0.8

when I tried to open tests\unicode.dot
it give error:

Traceback (most recent call last):
  File "C:\python34-64\lib\site-packages\xdot\ui\window.py", line 638, in on_open
    self.open_file(filename)
  File "C:\python34-64\lib\site-packages\xdot\ui\window.py", line 611, in open_file
    self.set_dotcode(fp.read(), filename)
  File "C:\python34-64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 32: character maps to <undefined>

**Comment by jrfonseca** [comment]
Thanks.  This issue could happen on Linux too if the locale was not set to UTF-8.

It should be fixed now in master, and in a future pypi release.
