### ISSUE TITLE
Dependency on graphviz

### ISSUE THREAD

**Issue by jebrosen** [jrfonseca/xdot.py#51]
A dependency on the `graphviz` package was added during the module splitting:
https://github.com/jrfonseca/xdot.py/commit/f0f03260684381e91a052e145b9b43a733d07dd2#diff-2eeaed663bd0d25b7e608891384b7298R35

This is at best unnecessary, as xdot calls the graphviz binaries directly. At worst, it causes the launcher script to abort if the `graphviz` package is not installed:

```
Traceback (most recent call last):
File "/usr/bin/xdot", line 6, in <module>
from pkg_resources import load_entry_point
File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
@_call_aside
File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
f(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
ws.require(__requires__)
File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'graphviz' distribution was not found and is required by xdot
```

Running xdot directly (e.g. `python3 -m xdot`) works fine. Is there a reason for this dependency or can it be dropped?

**Comment by jrfonseca** [comment]
CC'ing @ZedThree 

But I tend to agree.  Generally, trying to track dependencies of system (non-python) packages with python packaging tends to cause more issues than it solves.

**Comment by jebrosen** [comment]
Clarification note I missed in the original post: the python package `graphviz` is not even graphviz itself; it is another wrapper around graphviz. The "real" graphviz does have a python package called `gv`, but xdot does not use that either.

**Comment by jrfonseca** [comment]
Indeed that removes all doubt for me.  Thanks guys.
