### ISSUE TITLE
When there is a subgraph connecting to a node and use fdp as the filter, xdot crashes.

### ISSUE THREAD

**Issue by xuhdev** [jrfonseca/xdot.py#69]
To reproduce, save the following to `test.dot`:

```dot
graph {
  subgraph cluster_x {
    label = "hello";
  }

  cluster_x -- a;
}
```

`fdp -Tsvg test.dot > test.svg` generates a proper svg file. But running `xdot -f fdp test.dot` leads to the following error:

```
Traceback (most recent call last):
  File "/home/hong/.local/bin/xdot", line 10, in <module>
    sys.exit(main())
  File "/home/hong/.local/lib/python3.7/site-packages/xdot/__main__.py", line 77, in main
    win.open_file(inputfile)
  File "/home/hong/.local/lib/python3.7/site-packages/xdot/ui/window.py", line 615, in open_file
    self.set_dotcode(fp.read(), filename)
  File "/home/hong/.local/lib/python3.7/site-packages/xdot/ui/window.py", line 597, in set_dotcode
    if self.dotwidget.set_dotcode(dotcode, filename):
  File "/home/hong/.local/lib/python3.7/site-packages/xdot/ui/window.py", line 141, in set_dotcode
    if self._set_dotcode(dotcode, filename, center=center):
  File "/home/hong/.local/lib/python3.7/site-packages/xdot/ui/window.py", line 132, in _set_dotcode
    self.set_xdotcode(xdotcode, center=center)
  File "/home/hong/.local/lib/python3.7/site-packages/xdot/ui/window.py", line 152, in set_xdotcode
    self.graph = parser.parse()
  File "/home/hong/.local/lib/python3.7/site-packages/xdot/dot/parser.py", line 519, in parse
    DotParser.parse(self)
  File "/home/hong/.local/lib/python3.7/site-packages/xdot/dot/parser.py", line 309, in parse
    self.parse_graph()
  File "/home/hong/.local/lib/python3.7/site-packages/xdot/dot/parser.py", line 318, in parse_graph
    self.parse_stmt()
  File "/home/hong/.local/lib/python3.7/site-packages/xdot/dot/parser.py", line 358, in parse_stmt
    self.handle_edge(node_ids[i], node_ids[i + 1], attrs)
  File "/home/hong/.local/lib/python3.7/site-packages/xdot/dot/parser.py", line 514, in handle_edge
    src = self.node_by_name[src_id]
KeyError: b'cluster_x'
```

**Comment by jrfonseca** [comment]
It works for me when I try xdot from master.  I think this is the same issue #65 which.

I think I should release a new Xdot version with the fix.
