### ISSUE TITLE
traceback printed to stderr when cursor theme doesn't contain HAND2 icon

### ISSUE THREAD

**Issue by paper42** [jrfonseca/xdot.py#89]
```
Gdk-Message: 00:34:00.087: Unable to load hand2 from the cursor theme
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/xdot/ui/window.py", line 449, in on_area_motion_notify
    self.drag_action.on_motion_notify(event)
  File "/usr/lib/python3.9/site-packages/xdot/ui/actions.py", line 87, in on_motion_notify
    new_cursor = Gdk.Cursor(Gdk.CursorType.HAND2)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gdk.py", line 329, in __new__
    return cls.new(*args, **kwds)
TypeError: constructor returned NULL
```
xdot continues working as expected

**Comment by jrfonseca** [comment]
I google around for this, and per https://gitlab.gnome.org/World/lollypop/-/issues/1185 it sounds this is a configuration issue.

It sounds like you're missing the fallback cursor theme?

**Comment by paper42** [comment]
I am not sure what exactly is happening, because I am using the default Adwaita theme in GNOME. Other application print similar error messages, so this is not an issue in xdot. Thank you for your help.
